resolver: lts-20.3  # use `stack ls snapshots --lts remote` for a list of possible resolvers

packages:
- .

extra-deps:
- hakyll-4.15.1.1  # Or a later version you installed
- datetime-0.3.1
- strptime-1.0.10
- blagda-0.1.0.1
- Agda-2.6.2.1


allow-newer: true
